AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.4
  Include:
    - 'app/**/*.rb'
    - 'lib/**/*.rb'
    - 'lib/**/*.rake'
  Exclude:
    - 'Gemfile'
    - 'Guardfile'
    - 'Rakefile'
    - 'bin/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
Metrics/LineLength:
  Max: 120
  Exclude:
    - spec/**/*
Style/Documentation:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/FrozenStringLiteralComment:
  Enabled: false
Layout/IndentArray:
  EnforcedStyle: consistent
Style/GlobalVars:
  Enabled: false
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: aligned
Style/Alias:
  EnforcedStyle: prefer_alias_method
Style/Lambda:
  EnforcedStyle: lambda
Style/IfUnlessModifier:
  Enabled: false
Style/GuardClause:
  MinBodyLength: 3
Style/RaiseArgs:
  EnforcedStyle: compact
Style/SpecialGlobalVars:
  EnforcedStyle: use_perl_names
Metrics/BlockLength:
  Exclude:
    - spec/**/*
