sudo: false
language: ruby
cache: bundler
rvm:
  - 2.6.0
addons:
  postgresql: '9.4'
env:
- JWT_SECRET_KEY=df4eb72858852f57d15d8d6dd53b305e
before_script:
- psql -c 'create database sinatra_api_test;' -U postgres
script:
- bin/rake db:migrate APP_ENV=test
- bin/rake ci:all
